config/routes.rb
Rails.application.routes.draw do
  resources :dados
  resources :testes

end

app/models/dado.rb
class Dado < ActiveRecord::Base
end

app/models/teste.rb
class Teste < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dados_controller.rb
class DadosController < ApplicationController
  before_action :set_dado, only: [:show, :edit, :update, :destroy]

  # GET /dados
  # GET /dados.json
  def index
    @dados = Dado.all
  end

  # GET /dados/1
  # GET /dados/1.json
  def show
  end

  # GET /dados/new
  def new
    @dado = Dado.new
  end

  # GET /dados/1/edit
  def edit
  end

  # POST /dados
  # POST /dados.json
  def create
    @dado = Dado.new(dado_params)

    respond_to do |format|
      if @dado.save
        format.html { redirect_to @dado, notice: 'Dado was successfully created.' }
        format.json { render :show, status: :created, location: @dado }
      else
        format.html { render :new }
        format.json { render json: @dado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dados/1
  # PATCH/PUT /dados/1.json
  def update
    respond_to do |format|
      if @dado.update(dado_params)
        format.html { redirect_to @dado, notice: 'Dado was successfully updated.' }
        format.json { render :show, status: :ok, location: @dado }
      else
        format.html { render :edit }
        format.json { render json: @dado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dados/1
  # DELETE /dados/1.json
  def destroy
    @dado.destroy
    respond_to do |format|
      format.html { redirect_to dados_url, notice: 'Dado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dado
      @dado = Dado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dado_params
      params.require(:dado).permit(:nome)
    end
end

app/controllers/testes_controller.rb
class TestesController < ApplicationController
  before_action :set_testis, only: [:show, :edit, :update, :destroy]

  # GET /testes
  # GET /testes.json
  def index
    @testes = Teste.all
  end

  # GET /testes/1
  # GET /testes/1.json
  def show
  end

  # GET /testes/new
  def new
    @testis = Teste.new
  end

  # GET /testes/1/edit
  def edit
  end

  # POST /testes
  # POST /testes.json
  def create
    @testis = Teste.new(testis_params)

    respond_to do |format|
      if @testis.save
        format.html { redirect_to @testis, notice: 'Teste was successfully created.' }
        format.json { render :show, status: :created, location: @testis }
      else
        format.html { render :new }
        format.json { render json: @testis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testes/1
  # PATCH/PUT /testes/1.json
  def update
    respond_to do |format|
      if @testis.update(testis_params)
        format.html { redirect_to @testis, notice: 'Teste was successfully updated.' }
        format.json { render :show, status: :ok, location: @testis }
      else
        format.html { render :edit }
        format.json { render json: @testis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testes/1
  # DELETE /testes/1.json
  def destroy
    @testis.destroy
    respond_to do |format|
      format.html { redirect_to testes_url, notice: 'Teste was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testis
      @testis = Teste.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testis_params
      params.require(:testis).permit(:nome, :email, :telefone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dados_helper.rb
module DadosHelper
end

app/helpers/testes_helper.rb
module TestesHelper
end

app/views/dados/_form.html.erb
<%= form_for(@dado) do |f| %>
  <% if @dado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dado.errors.count, "error") %> prohibited this dado from being saved:</h2>

      <ul>
      <% @dado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dados/edit.html.erb
<h1>Editing Dado</h1>

<%= render 'form' %>

<%= link_to 'Show', @dado %> |
<%= link_to 'Back', dados_path %>

app/views/dados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dados</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dados.each do |dado| %>
      <tr>
        <td><%= dado.nome %></td>
        <td><%= link_to 'Show', dado %></td>
        <td><%= link_to 'Edit', edit_dado_path(dado) %></td>
        <td><%= link_to 'Destroy', dado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dado', new_dado_path %>

app/views/dados/new.html.erb
<h1>New Dado</h1>

<%= render 'form' %>

<%= link_to 'Back', dados_path %>

app/views/dados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @dado.nome %>
</p>

<%= link_to 'Edit', edit_dado_path(@dado) %> |
<%= link_to 'Back', dados_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ACEV</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/testes/_form.html.erb
<%= form_for(@testis) do |f| %>
  <% if @testis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testis.errors.count, "error") %> prohibited this testis from being saved:</h2>

      <ul>
      <% @testis.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testes/edit.html.erb
<h1>Editing Testis</h1>

<%= render 'form' %>

<%= link_to 'Show', @testis %> |
<%= link_to 'Back', testes_path %>

app/views/testes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Testes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testes.each do |testis| %>
      <tr>
        <td><%= testis.nome %></td>
        <td><%= testis.email %></td>
        <td><%= testis.telefone %></td>
        <td><%= link_to 'Show', testis %></td>
        <td><%= link_to 'Edit', edit_testis_path(testis) %></td>
        <td><%= link_to 'Destroy', testis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teste', new_testis_path %>

app/views/testes/new.html.erb
<h1>New Testis</h1>

<%= render 'form' %>

<%= link_to 'Back', testes_path %>

app/views/testes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @testis.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @testis.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @testis.telefone %>
</p>

<%= link_to 'Edit', edit_testis_path(@testis) %> |
<%= link_to 'Back', testes_path %>